default: &default
  adapter: redis
  url: redis://localhost:6379

development:
  adapter: async

test:
  adapter: test

performance:
  <<: *default
  channel_prefix: campfire_performance

production:
  <<: *default
  channel_prefix: campfire_production
