default: &default
  adapter: redis
  url: redis://localhost:6379

development:
  adapter: async

test:
  adapter: <%= ENV.fetch("ACTION_CABLE_ADAPTER", "test") %>

performance:
  <<: *default
  channel_prefix: campfire_performance

production:
  <<: *default
  channel_prefix: campfire_production
